// src/templates/jest/config.ts
export function getJestConfigJs(): string {
  return `
// Auto-generated by AppSync TestGen
const path = require("node:path");

/** @type {import('jest').Config} */
module.exports = {
  // contexts/_shared/jest/jest.config.js → rootDir = contexts/
  rootDir: path.resolve(__dirname, "..", ".."),
  testEnvironment: "node",
  // We generate plain JS tests by default (no ts-jest dependency).
  testMatch: ["**/tests/jest/**/*.test.@(js|ts)"],
  reporters: [
    "default",
    "<rootDir>/_shared/jest/onfail-reporter.js"
  ],
};
`.trimStart();
}
