// v1 - top-level pytest shim conftest
// Returns the content for <testsRoot>/conftest.py
export default function getTopLevelConftestPy(): string {
  return `# Auto-generated by AppSync TestGen (top-level conftest shim)
from __future__ import annotations
import sys, pathlib

ROOT = pathlib.Path(__file__).parent.resolve()
SHARED = ROOT / "_shared" / "pytest"
if SHARED.exists():
    p = str(SHARED)
    if p not in sys.path:
        sys.path.insert(0, p)

# Load shared hooks (pytest will treat this module as plugin content)
try:
    import conftest_shared  # noqa: F401
except Exception as e:
    print("[appsync-testgen] warning: failed to import shared hooks:", e)
`;
}
