title: AppSync TestGen
description: "VS Code extension to generate and validate tests for AWS AppSync GraphQL APIs."
remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

show_downloads: true
# google_analytics: G-XXXXXXXXXX
